[package]
name = "near-facsimile"
version = "1.0.1"
edition = "2021"
rust-version = "1.57"
authors = ["Marek Suchánek <msuchane@redhat.com>"]
license = "Apache-2.0"
description = "Find similar or identical text files in a directory"
repository = "https://github.com/msuchane/near-facsimile/"
readme = "README.md"
keywords = ["duplicate", "similarity", "similar", "compare"]
categories = ["command-line-utilities", "text-processing"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color-eyre = "0.6"
strsim = "0.10"
rayon = "1.5"
log = "0.4"
simplelog = "0.12"
owo-colors = { version = "3.4", features = ["supports-colors"] }
csv = "1.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap = { version = "3.2", features = ["derive", "cargo"] }
permutator = "0.4"
trigram = "0.4"
ignore = "0.4"
regex = "1.6"
indicatif = { version = "0.17", features = ["rayon"] }

[package.metadata.rpm]
package = "near-facsimile"

[package.metadata.rpm.cargo]
buildflags = ["--release"]

[package.metadata.rpm.targets]
near-facsimile = { path = "/usr/bin/near-facsimile" }
