[package]
name = "similar-adoc-modules"
version = "0.6.0"
edition = "2021"
rust-version = "1.58"
authors = ["Marek Suchánek <msuchane@redhat.com>"]
license = "Apache-2.0"
description = "Find similar or identical files in Red Hat documentation"
repository = "https://github.com/msuchane/similar-adoc-modules/"
readme = "README.md"
keywords = ["Red Hat", "documentation"]
categories = ["command-line-utilities", "text-processing"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color-eyre = "0.6"
strsim = "0.10"
rayon = "1.5"
log = "0.4"
simplelog = "0.12"
owo-colors = { version = "3.4", features = ["supports-colors"] }
csv = "1.1"
clap = { version = "3.2", features = ["derive", "cargo"] }
permutator = "0.4"
trigram = "0.4"

[package.metadata.rpm]
package = "similar-adoc-modules"

[package.metadata.rpm.cargo]
buildflags = ["--release"]

[package.metadata.rpm.targets]
similar-adoc-modules = { path = "/usr/bin/similar-adoc-modules" }
